# Sets thermostat to away mode if all mobile devices are away
- alias: 'Away Mode'
  trigger:
    - platform: state
      entity_id: group.device_trackers
      from: "home"
      to: "not_home"
  condition:
    - condition: state
      entity_id: group.device_trackers
      state: "not_home"
    - condition: state
      entity_id: input_boolean.location_override
      state: "off"
  action:
    - service: climate.set_away_mode
      entity_id:
       - climate.shikobee
      data:
        away_mode: true

# Sets thermostat to away mode if all mobile devices are away
- alias: 'End Away Mode'
  trigger:
    - platform: state
      entity_id: device_tracker.eiko_samsung
      from: "not_home"
      to: "home"
  condition:
    - condition: state
      entity_id: device_tracker.eiko_samsung
      state: "home"
    - condition: state
      entity_id: input_boolean.location_override
      state: "off"
  action:
    - service: climate.set_away_mode
      entity_id:
       - climate.shikobee
      data:
        away_mode: false

- alias: 'End Away Mode - Thor'
  trigger:
    - platform: state
      entity_id: device_tracker.thor_oneplus3
      from: "not_home"
      to: "home"
  condition:
    - condition: state
      entity_id: device_tracker.thor_oneplus3
      state: "home"
    - condition: state
      entity_id: input_boolean.location_override
      state: "off"
  action:
    - service: climate.set_away_mode
      entity_id:
       - climate.shikobee
      data:
        away_mode: false

#- alias: 'Update config if travis build is successfull'
#  trigger:
#    - platform: state
#      entity_id: sensor.travisci
#  condition:
#    - condition: state
#      entity_id: sensor.tweyterhomeassistantconfig_last_build_state
#      state: 'passed'
#  action:
#    - service: notify.thor_phone
#      data:
#        message: "Updating git to latest config."
#    - service: script.get_latest_config

- alias: 'Start door_to_garage_timer'
  trigger:
    - platform: state
      entity_id: sensor.door_to_garage
      from: "Closed"
      to: "Open"
  condition:
    - condition: state
      entity_id: sensor.door_to_garage
      state: "Open"
  action:
    service: script.door_to_garage_timer

- alias: 'Leaving home'
  trigger:
    - platform: state
      entity_id: sensor.garage_door
      from: "Closed"
      to: "Open"
  condition:
    - condition: state
      entity_id: sensor.garage_door
      state: "Open"
    - condition: state
      entity_id: input_boolean.doortogarage_timer
      state: "on"
  action:
    service: notify.thor_phone
    data:
      message: "Leaving the house"


- alias: 'Entry light on'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id: light.hue_white_lamp_2

- alias: 'Entry light off'
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue_white_lamp_2

- alias: 'Water in basement'
  trigger:
    - platform: state
      entity_id: sensor.basement_water_sensor
      from: "False"
      to: "True"
  action:
    service: notify.thor_phone
    data:
      message: "Water detected in basement"

