homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret degrees_latitude
  longitude: !secret degrees_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 290
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit
  # Customization file
  customize: !include customize.yaml

logger:

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: tweyter.duckdns.org

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

binary_sensor:
  - platform: rest
    name: Travis Status
    resource: https://api.travis-ci.org/repos/tweyter/HomeAssistantConfig/cc.json?branch=master
    scan_interval: 60
    value_template: "{{ value_json.last_build_status|int(1) == 0 }}"

sensor:
  - platform: yr
  - platform: template
    sensors:
      door_to_garage:
        friendly_name: Door to Garage
        value_template: '{% if is_state("sensor.hank_unknown_type0201_id0008_access_control", "23") %}Closed{% else %}Open{% endif %}'

      garage_door:
        friendly_name: Garage Door
        value_template: '{% if is_state("sensor.vision_zg8101_garage_door_detector_alarm_level", "255") %}Open{% else %}Closed{% endif %}'

      status_smoke_co_alarm:
        value_template: >-
          {%- if is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "13") %}
              Idle
          {%- elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "1") %}
              Fire Detected
          {%- elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "2") %}
              Carbon Monoxide Detected
          {%- elif is_state("sensor.first_alert_zcombo_smoke_and_carbon_monoxide_detector_alarm_type", "12") %}
              Alarm Testing
          {% else %}
              Unknown
          {%- endif %}
        friendly_name: 'Smoke/CO Alarm'

      battery_level_smoke_co_alarm:
        value_template: '{{states.zwave.first_alert_zcombo_smoke_and_carbon_monoxide_detector.attributes.battery_level}}'
        friendly_name: 'Smoke/CO Alarm Battery'
        unit_of_measurement: '%'
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: rest
    name: Travis Status Label
    resource: https://api.travis-ci.org/repos/tweyter/HomeAssistantConfig/cc.json?branch=master
    scan_interval: 60
    value_template: "{{ value_json.last_build_number }}"
  - platform: darksky
    api_key: !secret dark_sky_key
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
  - platform: cert_expiry
    host: tweyter.duckdns.org
    name: DuckDNS SSL Certificate Expiry

#  - platform: ring
#    monitored_conditions:
#      - battery
#      - last_activity
#      - last_ding
#      - last_motion
#      - volume

# Text to speech
tts:
  - platform: google

# Ecobee
ecobee:
  api_key: !secret ecobee_api_key

# zwave
zwave:
  usb_path: /dev/zwave

# Ring doorbell
#ring:
#  username: !secret ring_username
#  password: !secret ring_password

# Roku Media player and Pandora music player
media_player:
  - platform: roku
  - platform: pandora

# Pushover push notifications
notify:
  - name: thor_phone
    platform: pushover
    api_key: !secret pushover_api_thor
    user_key: !secret pushover_user_thor
  - name: eiko_phone
    platform: pushover
    api_key: !secret pushover_api_eiko
    user_key: !secret pushover_user_eiko

device_tracker:
  - platform: owntracks_http
    max_gps_accuracy: 200
  - platform: tplink
    host: 192.168.0.1
    username: !secret tplink_username
    password: !secret tplink_password

zone:
  - name: Home
    latitude: !secret degrees_latitude
    longitude: !secret degrees_longitude
    radius: 200
    icon: mdi:account-multiple

input_boolean:
  doortogarage_timer:
    name: Timer that is started when the door to the garage is opened.
    initial: off

group: !include groups.yaml
automation: !include_dir_list automations
script: !include scripts.yaml
